version: "3.9"

services:
  server:
    image: jaykay24/fbi-most-wanted:1.0.0
    ports:
      - "3000:3000"
    restart: always

  client:
    depends_on:
      - server
    image: jaykay24/fbi-most-wanted-client:1.0.0
    ports:
      - "5173:5173"
    restart: always
