version: "3.9"

services:
  fbi_most_wanted_db:
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - fbi_data:/data/db

  server:
    depends_on:
      - fbi_most_wanted_db
    image: jaykay24/fbi-most-wanted-server:1.0.0
    ports:
      - "3000:3000"
    restart: always

  client:
    depends_on:
      - server
    image: jaykay24/fbi-most-wanted-client:1.0.0
    ports:
      - "3001:3000"
    restart: always
volumes:
  fbi_data:
